package uz.abumme.harfgame.tools.wordlists

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonPrimitive
import uz.abumme.harfgame.engine.Tokenizer
import uz.abumme.harfgame.lang.LaunchLanguages
import uz.abumme.harfgame.lang.UzbekDailyWords
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.exists
import kotlin.io.path.readLines
import kotlin.io.path.writeText

/**
 * What one language's regenerated guess dictionary contains; [packJsonBytes] is its guess list as served JSON and
 * [sourceWords] how many playable words each source contributed before merging (sources overlap).
 */
data class GuessListReport(
    val lang: String,
    val words: Int,
    val added: Int,
    val packJsonBytes: Int,
    val sourceWords: Map<String, Int> = emptyMap(),
)

/**
 * Writes a language's guess dictionary to both copies — the backend's, which the server merges into stored packs,
 * and the bundled one offline apps play from. Contents: the builder's candidates plus every previous guess, every
 * answer and, for Uzbek, the daily words, minus blocklisted words; each in its canonical spelling so a word appears
 * once however it was typed, sorted for stable diffs, under an attribution header (design.md, "Selection rules" 6–7).
 */
class GuessListWriter(private val repoRoot: Path, private val dumpDate: String) {

    /** [extraSources] are header lines crediting sources beyond Wiktionary, one per source. */
    fun write(lang: String, candidates: Set<String>, extraSources: List<String> = emptyList()): GuessListReport {
        val canonical = canonicalizer(lang)
        val copies = listOf(backend("${lang}_guess.txt"), bundled("${lang}_guess.txt"))
        val previous = copies.flatMap(::words).mapTo(HashSet(), canonical)
        val answers = words(backend("${lang}_answers.txt")).map(canonical)
        val dailyWords = UzbekDailyWords.lexemes.mapNotNull { it.graphemes(lang)?.joinToString("") }
        val blocked = (words(bundled("${lang}_block.txt")) + words(suggestionBlocklist("${lang}_block.txt")))
            .mapTo(HashSet(), canonical)

        val guesses = (candidates.map(canonical) + previous + answers + dailyWords)
            .filterNot { it in blocked }
            .toSortedSet()
        val text = header(lang, extraSources) + guesses.joinToString(separator = "\n", postfix = "\n")
        for (copy in copies) {
            copy.parent.createDirectories()
            copy.writeText(text)
        }
        return GuessListReport(
            lang = lang,
            words = guesses.size,
            added = guesses.count { it !in previous },
            packJsonBytes = JsonArray(guesses.map { JsonPrimitive(it) }).toString().toByteArray().size,
        )
    }

    /** The game's spelling of a word (lowercase, canonical apostrophes and letters); unchanged if it doesn't tokenize. */
    private fun canonicalizer(lang: String): (String) -> String {
        val tokenizer = LaunchLanguages.all[lang]?.let(::Tokenizer)
        return { word -> tokenizer?.tokenize(word)?.joinToString("") ?: word.lowercase() }
    }

    private fun header(lang: String, extraSources: List<String>) = (
        listOf(
            "# $lang guess dictionary, generated by tools/wordlists. Don't edit by hand: blocklist rejected words and rebuild.",
            "# Source: Wiktionary (https://www.wiktionary.org/) contributors, extracted with Wiktextract via kaikki.org; dump downloaded $dumpDate.",
            "# License: CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/). See THIRD_PARTY_NOTICES.md.",
        ) + extraSources.map { "# Source: $it" }
        ).joinToString(separator = "\n", postfix = "\n")

    private fun backend(name: String): Path = repoRoot.resolve("backend/src/main/resources/wordpacks/$name")
    private fun bundled(name: String): Path = repoRoot.resolve("sharedUI/src/commonMain/composeResources/files/$name")
    private fun suggestionBlocklist(name: String): Path = repoRoot.resolve("backend/src/main/resources/blocklists/$name")

    /** A list file's words: trimmed, without blank lines or `#` comments; empty when the file is absent. */
    private fun words(file: Path): List<String> =
        if (!file.exists()) emptyList()
        else file.readLines().map { it.trim().removePrefix("﻿") }.filter { it.isNotEmpty() && !it.startsWith("#") }
}
